services:
  - type: web
    name: project-management-tool
    env: node
    buildCommand: npm run install-client && npm run install-server && npm run build-client && npm run build-server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
